spring:
    application:
        name: peak-space-b12
        url: jdbc:postgresql://localhost:5432/peakspace
        username: postgres
        password: mirlan001m.

    jpa:
        hibernate:
            ddl-auto: create

        show-sql: true

server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: Employees