package peakspace.enums;

public enum Country {
        AFGHANISTAN("Афганистан"),
        ALBANIA("Албания"),
        ALGERIA("Алжир"),
        ANDORRA("Андорра"),
        ANGOLA("Ангола"),
        ANTIGUA_AND_BARBUDA("Антигуа и Барбуда"),
        ARGENTINA("Аргентина"),
        ARMENIA("Армения"),
        AUSTRALIA("Австралия"),
        AUSTRIA("Австрия"),
        AZERBAIJAN("Азербайджан"),
        BAHAMAS("Багамы"),
        BAHRAIN("Бахрейн"),
        BANGLADESH("Бангладеш"),
        BARBADOS("Барбадос"),
        BELARUS("Беларусь"),
        BELGIUM("Бельгия"),
        BELIZE("Белиз"),
        BENIN("Бенин"),
        BHUTAN("Бутан"),
        BOLIVIA("Боливия"),
        BOSNIA_AND_HERZEGOVINA("Босния и Герцеговина"),
        BOTSWANA("Ботсвана"),
        BRAZIL("Бразилия"),
        BRUNEI("Бруней"),
        BULGARIA("Болгария"),
        BURKINA_FASO("Буркина-Фасо"),
        BURUNDI("Бурунди"),
        CABO_VERDE("Кабо-Верде"),
        CAMBODIA("Камбоджа"),
        CAMEROON("Камерун"),
        CANADA("Канада"),
        CENTRAL_AFRICAN_REPUBLIC("Центральноафриканская Республика"),
        CHAD("Чад"),
        CHILE("Чили"),
        CHINA("Китай"),
        COLOMBIA("Колумбия"),
        COMOROS("Коморы"),
        CONGO("Конго"),
        COSTA_RICA("Коста-Рика"),
        CROATIA("Хорватия"),
        CUBA("Куба"),
        CYPRUS("Кипр"),
        CZECH_REPUBLIC("Чехия"),
        DENMARK("Дания"),
        DJIBOUTI("Джибути"),
        DOMINICA("Доминика"),
        DOMINICAN_REPUBLIC("Доминиканская Республика"),
        ECUADOR("Эквадор"),
        EGYPT("Египет"),
        EL_SALVADOR("Сальвадор"),
        EQUATORIAL_GUINEA("Экваториальная Гвинея"),
        ERITREA("Эритрея"),
        ESTONIA("Эстония"),
        ESWATINI("Эсватини"),
        ETHIOPIA("Эфиопия"),
        FIJI("Фиджи"),
        FINLAND("Финляндия"),
        FRANCE("Франция"),
        GABON("Габон"),
        GAMBIA("Гамбия"),
        GEORGIA("Грузия"),
        GERMANY("Германия"),
        GHANA("Гана"),
        GREECE("Греция"),
        GRENADA("Гренада"),
        GUATEMALA("Гватемала"),
        GUINEA("Гвинея"),
        GUINEA_BISSAU("Гвинея-Бисау"),
        GUYANA("Гайана"),
        HAITI("Гаити"),
        HONDURAS("Гондурас"),
        HUNGARY("Венгрия"),
        ICELAND("Исландия"),
        INDIA("Индия"),
        INDONESIA("Индонезия"),
        IRAN("Иран"),
        IRAQ("Ирак"),
        IRELAND("Ирландия"),
        ISRAEL("Израиль"),
        ITALY("Италия"),
        JAMAICA("Ямайка"),
        JAPAN("Япония"),
        JORDAN("Иордания"),
        KAZAKHSTAN("Казахстан"),
        KENYA("Кения"),
        KIRIBATI("Кирибати"),
        KOSOVO("Косово"),
        KUWAIT("Кувейт"),
        KYRGYZSTAN("Кыргызстан"),
        LAOS("Лаос"),
        LATVIA("Латвия"),
        LEBANON("Ливан"),
        LESOTHO("Лесото"),
        LIBERIA("Либерия"),
        LIBYA("Ливия"),
        LIECHTENSTEIN("Лихтенштейн"),
        LITHUANIA("Литва"),
        LUXEMBOURG("Люксембург"),
        MADAGASCAR("Мадагаскар"),
        MALAWI("Малави"),
        MALAYSIA("Малайзия"),
        MALDIVES("Мальдивы"),
        MALI("Мали"),
        MALTA("Мальта"),
        MARSHALL_ISLANDS("Маршалловы Острова"),
        MAURITANIA("Мавритания"),
        MAURITIUS("Маврикий"),
        MEXICO("Мексика"),
        MICRONESIA("Микронезия"),
        MOLDOVA("Молдова"),
        MONACO("Монако"),
        MONGOLIA("Монголия"),
        MONTENEGRO("Черногория"),
        MOROCCO("Марокко"),
        MOZAMBIQUE("Мозамбик"),
        MYANMAR("Мьянма"),
        NAMIBIA("Намибия"),
        NAURU("Науру"),
        NEPAL("Непал"),
        NETHERLANDS("Нидерланды"),
        NEW_ZEALAND("Новая Зеландия"),
        NICARAGUA("Никарагуа"),
        NIGER("Нигер"),
        NIGERIA("Нигерия"),
        NORTH_KOREA("Северная Корея"),
        NORTH_MACEDONIA("Северная Македония"),
        NORWAY("Норвегия"),
        OMAN("Оман"),
        PAKISTAN("Пакистан"),
        PALAU("Палау"),
        PANAMA("Панама"),
        PAPUA_NEW_GUINEA("Папуа — Новая Гвинея"),
        PARAGUAY("Парагвай"),
        PERU("Перу"),
        PHILIPPINES("Филиппины"),
        POLAND("Польша"),
        PORTUGAL("Португалия"),
        QATAR("Катар"),
        ROMANIA("Румыния"),
        RUSSIA("Россия"),
        RWANDA("Руанда"),
        SAN_MARINO("Сан-Марино");

        private final String russianName;

        Country(String russianName) {
                this.russianName = russianName;
        }

        public String getRussianName() {
                return russianName;
        }
}
