# Amazon S3
cloud:
  aws:
    region: eu-central-1
    access-key: AKIA3KYNRCVIBB2TALRT
    secret-key: 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
  s3:
    bucketName: peakspace-b12

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 22MB
      max-file-size: 100MB
      max-request-size: 100MB