spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nurtaazimmukanov24@gmail.com
    password: zzao pnpb wrot lrlk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      defer-datasource-initialization: true