spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: arstanbeekovvv@gmail.com
    password: gnfh xali juew hdna
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      defer-datasource-initialization: true